#### Color Calibration
Contains code to take a sample image with known color targets and find the color correction matrix which best approximates the transformation from observed to theoretical color spaces.

In [113]:
import numpy as np
import scipy.spatial as space
import scipy.stats as stats

In [70]:
def MeasureColorCorrection(X,Y):
    cov = np.matmul(np.transpose(X), Y)
    U, S, Vt = np.linalg.svd(cov)
    V = np.transpose(Vt)
    Ut = np.transpose(U)
    VUt = np.matmul(V, Ut)
    d = np.linalg.det(VUt)
    print(d)
    CCM = np.matmul(V, np.matmul(np.diag([1,1,d]), Ut))
    return CCM

In [71]:
Observed_Data = np.random.rand(1000,3)
color_correction_matrix = stats.ortho_group.rvs(3)#np.random.rand(3,3)

In [83]:
centroids = np.mean(Observed_Data,0)
Observed_Data = np.subtract(Observed_Data, centroids)

In [123]:
y_perfect = np.matmul(Observed_Data, color_correction_matrix)
y_test = np.add(np.matmul(Observed_Data, color_correction_matrix), 0.01 * np.random.randn(1000,3))
y_test = np.subtract(y_test, np.mean(y_test,0))
ccm = MeasureColorCorrection(Observed_Data, y_test)
print(ccm)
y_ccm = np.matmul(Observed_Data, ccm)

-1.0000000000000002
[[-0.07294375  0.96996409  0.23205359]
 [-0.95522904 -0.13484038  0.26335442]
 [ 0.28673452 -0.20245426  0.93637364]]


In [124]:
print(y_perfect[0:3,:])
print('\n')
print(y_test[0:3,:])
print('\n')
print(y_ccm[0:3,:])

[[ 0.51174662  0.26333612 -0.28489922]
 [ 0.19734383 -0.24881009  0.71661283]
 [-0.16208416  0.33134522 -0.41864969]]


[[ 0.51745559  0.26578396 -0.28329771]
 [ 0.19966632 -0.25624228  0.71733218]
 [-0.15860347  0.33681645 -0.40724026]]


[[ 0.55209837 -0.29544229  0.14247571]
 [-0.35642085  0.22382036  0.66125156]
 [ 0.16752098 -0.31287663 -0.43055014]]


In [125]:
print(color_correction_matrix)
print(ccm)

[[ 0.04193588 -0.97847082  0.2020798 ]
 [-0.48008896  0.15764345  0.86293866]
 [ 0.87621685  0.13320437  0.46314212]]
[[-0.07294375  0.96996409  0.23205359]
 [-0.95522904 -0.13484038  0.26335442]
 [ 0.28673452 -0.20245426  0.93637364]]


In [50]:
cov = np.matmul(np.transpose(X), Y)
U, S, Vt = np.linalg.svd(cov)
V = np.transpose(Vt)
Ut = np.transpose(U)
VUt = np.matmul(V, Ut)
d = np.linalg.det(VUt)
print(d)

-0.9999999999999996


In [ ]:
np.linalg()